# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: write
  id-token: write
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v4

     - name: Use Node.js
       uses: actions/setup-node@v4
       with:
         node-version: '22'
    
     - run: npm ci
     - run: npm run build
    
      # Adjust the directory below ('dist' or 'build') to your actual build output
     - name: Upload build output as artifact
       uses: actions/upload-artifact@v4
       with:
         name: build-output
         path: dist
    
     - name: Deploy to GitHub Pages
       if: github.ref == 'refs/heads/main'
       uses: peaceiris/actions-gh-pages@v4
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: ./dist
      
